services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - '3001:3001'
