services:
  postgres:
    image: postgres:16-alpine
    container_name: backend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: system_control
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/system_control
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: system_control
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRATION: 15m
      PORT: 3000
      NODE_ENV: production
      FRONTEND_URL: http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
